# baseImage 를 명시해준다. <이미지 이름> : <tag> -> 태그를 안붙이면 가장 최신것을 다운 받음.
# FROM baseImage

# 추가적으로 필요한 파일을 다운로드 받는다.
# RUN command

# Container 시작 시 실행 될 명령어를 명시해준다.
# CMD ["executable"]

FROM alpine
CMD ["echo", "hello"]
